# Paths for Kaggle Environment
# Lưu ý: Thay 'YOUR_DATASET_NAME' bằng tên thư mục dataset thực tế của bạn trên Kaggle
DATA_DIR: '/kaggle/input/datasets/nadkli/data-agriculture/dataset' 
CHECKPOINT_DIR: '/kaggle/working/checkpoints' # /kaggle/working là thư mục duy nhất cho phép ghi file

# Đường dẫn dữ liệu hình ảnh (Read-only từ dataset)
TRAIN_DIR: '/kaggle/input/datasets/nadkli/data-agriculture/dataset/train' 
VAL_DIR: '/kaggle/input/datasets/nadkli/data-agriculture/dataset/val' 
TRAIN_RGB_DIR: '/kaggle/input/datasets/nadkli/data-agriculture/dataset/train/RGB' 
VAL_RGB_DIR: '/kaggle/input/datasets/nadkli/data-agriculture/dataset/val/RGB' 

# Thư mục gốc để lưu file submission.csv
ROOT_DIR: '/kaggle/working' 