# Paths (relative to project root)
DATA_DIR: 'data/raw' # Thư mục chứa dữ liệu gốc
CHECKPOINT_DIR: 'checkpoints' # Thư mục lưu trọng số mô hình đã huấn luyện
TRAIN_DIR: 'data/raw/train' # Thư mục chứa dữ liệu huấn luyện
TEST_DIR: 'data/raw/test' # Thư mục chứa dữ liệu kiểm thử
TRAIN_RGB_DIR: 'data/raw/train/RGB' # Thư mục chứa ảnh RGB huấn luyện
TEST_RGB_DIR: 'data/raw/test/RGB' # Thư mục chứa ảnh RGB kiểm thử
SAMPLES_MASTER: 'notebooks/split/splits/samples_master.csv' # File CSV tổng hợp thông tin mẫu dữ liệu
TRAIN_IDX_FILE: 'notebooks/split/splits/train_idx.npy' # File lưu chỉ số tập huấn luyện
VAL_IDX_FILE: 'notebooks/split/splits/val_idx.npy' # File lưu chỉ số tập validation
ROOT_DIR: '.' # Thư mục gốc của dự án
